name: "Create Release"
on:
    push:
        tags:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: Install NPM dependencies
              run: npm ci

            - name: Test
              run: npm run test

            - name: Build
              run: npm run build

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  name: Release ${{ github.ref_name }}
                  files: |
                      main.js
                      manifest.json
